package com.gree.model

case  class Tbl_Az_Assign_Pslc_Ls(
                                   pgguid	: String, // varchar(255) NOT NULL,
                                   created_by	: String, // varchar(255) DEFAULT NULL,
                                   created_date	: String, // datetime DEFAULT NULL,
                                   last_modified_by	: String, // varchar(255) DEFAULT NULL,
                                   last_modified_date	: String, // datetime DEFAULT NULL,
                                   azren	: String, // varchar(30) DEFAULT NULL COMMENT '安装人',
                                   azrenid	: String, // bigint(64) DEFAULT '0' COMMENT '安装人ID',
                                   azsl	: String, // int(11) DEFAULT '0' COMMENT '安装数量',
                                   azwdmc	: String, // varchar(80) DEFAULT NULL COMMENT '安装网点名称',
                                   azwdno	: String, // varchar(8) DEFAULT NULL COMMENT '安装网点号',
                                   azwdxtbh	: String, // varchar(10) DEFAULT NULL COMMENT '安装网点系统编号',
                                   beiz	: String, // varchar(1600) DEFAULT NULL COMMENT '备注',
                                   bjustat	: String, // int(11) DEFAULT '0' COMMENT '检测北交云扫描状态',
                                   cjdt	: String, // datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'cjdt',
                                   cjren	: String, // varchar(80) DEFAULT NULL COMMENT '创建人',
                                   cjrmc	: String, // varchar(80) DEFAULT NULL COMMENT '创建人名称',
                                   cjwdno	: String, // varchar(10) DEFAULT NULL COMMENT '创建网点',
                                   cjwdxtbh	: String, // varchar(10) DEFAULT NULL COMMENT '创建网点系统编号',
                                   cshi	: String, // varchar(40) DEFAULT NULL COMMENT '市',
                                   dhhm	: String, // varchar(16) DEFAULT NULL COMMENT '电话号码',
                                   dizi	: String, // varchar(200) DEFAULT NULL COMMENT '详细地址',
                                   djlxno	: String, // varchar(10) DEFAULT NULL COMMENT '单据类型编号',
                                   dqjd	: String, // bigint(64) DEFAULT '0' COMMENT '当前节点',
                                   dqjdsj	: String, // datetime DEFAULT CURRENT_TIMESTAMP COMMENT '当前节点时间',
                                   email	: String, // varchar(100) DEFAULT NULL COMMENT '邮件',
                                   fjhm	: String, // varchar(10) DEFAULT NULL COMMENT '分机号',
                                   fphm	: String, // varchar(20) DEFAULT NULL COMMENT '发票号码',
                                   gcbh	: String, // varchar(30) DEFAULT NULL COMMENT '工程编号',
                                   gcmc	: String, // varchar(100) DEFAULT NULL COMMENT '工程名称',
                                   gdhao	: String, // varchar(40) DEFAULT NULL COMMENT '工单号',
                                   gmsj	: String, // datetime DEFAULT NULL COMMENT '购买日期',
                                   gpsdzxx	: String, // varchar(130) DEFAULT NULL COMMENT 'GPS地址信息',
                                   jindu	: String, // varchar(50) DEFAULT NULL COMMENT '进度',
                                   jspgwdmc	: String, // varchar(80) DEFAULT NULL COMMENT '接收派工网名称',
                                   jspgwdno	: String, // varchar(8) DEFAULT NULL COMMENT '接收派工网点号',
                                   jspgwdsj	: String, // datetime DEFAULT NULL COMMENT '接收派工网点时间',
                                   jspgwdxtbh	: String, // varchar(10) DEFAULT NULL COMMENT '接收派工信息网点编号',
                                   kqbh	: String, // varchar(50) DEFAULT NULL COMMENT '跨区编号',
                                   lcid	: String, // varchar(40) DEFAULT NULL COMMENT '流程序号',
                                   lxren	: String, // varchar(80) DEFAULT NULL COMMENT '联系人',
                                   pgid	: String, // varchar(40) DEFAULT NULL COMMENT '派工序号',
                                   qqlymc	: String, // varchar(30) DEFAULT NULL COMMENT '信息方式名称',
                                   qqlyno	: String, // varchar(10) DEFAULT NULL COMMENT '来源系统',
                                   qqlyxh	: String, // varchar(40) DEFAULT NULL COMMENT '来源序号',
                                   qqlyzj	: String, // varchar(100) DEFAULT NULL COMMENT '来源系统主信息主键',
                                   quhao	: String, // varchar(5) DEFAULT NULL COMMENT '区号',
                                   sfen	: String, // varchar(20) DEFAULT NULL COMMENT '省份',
                                   sfwcps	: String, // varchar(150) DEFAULT NULL COMMENT '是否完成配送',
                                   sfygllc	: String, // int(11) DEFAULT '0' COMMENT '是否有关联流程',
                                   shsj	: String, // datetime DEFAULT NULL COMMENT '送货时间',
                                   spid	: String, // bigint(64) DEFAULT '0' COMMENT '商品类别序号',
                                   spmc	: String, // varchar(20) DEFAULT NULL COMMENT '商品名称',
                                   ssqy	: String, // varchar(8) DEFAULT NULL COMMENT '所属区域',
                                   stat	: String, // int(11) DEFAULT '0' COMMENT '派工状态',
                                   syjd	: String, // bigint(64) DEFAULT '0' COMMENT '上一节点',
                                   weidu	: String, // varchar(50) DEFAULT NULL COMMENT '纬度',
                                   wwsl	: String, // int(11) DEFAULT '0' COMMENT '未完数量',
                                   xian	: String, // varchar(40) DEFAULT NULL COMMENT '区县',
                                   xsdh	: String, // varchar(40) DEFAULT NULL COMMENT '销售单号',
                                   xsdwno	: String, // varchar(8) DEFAULT NULL COMMENT '销售网点号',
                                   xsdwxtbh	: String, // varchar(10) DEFAULT NULL COMMENT '销售单位系统网点编号',
                                   xslx	: String, // varchar(20) DEFAULT NULL COMMENT '销售类型',
                                   xsorsh	: String, // int(11) DEFAULT '1' COMMENT '数据录入属性',
                                   xswdmc	: String, // varchar(120) DEFAULT NULL COMMENT '销售单位名称',
                                   xxlb	: String, // varchar(40) DEFAULT NULL COMMENT '信息类别',
                                   xxly	: String, // varchar(40) DEFAULT NULL COMMENT '信息来源',
                                   xxqd	: String, // varchar(40) DEFAULT NULL COMMENT '信息渠道',
                                   xzhen	: String, // varchar(100) DEFAULT NULL COMMENT '街道办/乡镇',
                                   yddh	: String, // varchar(11) DEFAULT NULL COMMENT '移动电话',
                                   yddh2	: String, // varchar(11) DEFAULT NULL COMMENT '移动电话2',
                                   yhmc	: String, // varchar(80) DEFAULT NULL COMMENT '用户姓名',
                                   yhqwjssj	: String, // datetime DEFAULT NULL COMMENT '用户期望上门结束时间',
                                   yhqwkssj	: String, // datetime DEFAULT NULL COMMENT '用户期望上门开始时间',
                                   yhsx	: String, // varchar(20) DEFAULT NULL COMMENT '用户属性',
                                   yxji	: String, // varchar(10) DEFAULT NULL COMMENT '优先级',
                                   yyazsj	: String, // datetime DEFAULT NULL COMMENT '预约安装时间',
                                   zjczren	: String, // varchar(80) DEFAULT NULL COMMENT '最近操作人',
                                   zjczsj	: String, // datetime DEFAULT NULL COMMENT '最近操作时间',
                                   zjczwd	: String, // varchar(10) DEFAULT NULL COMMENT '最近操作网点',
                                   zjczwdxtbh	: String, // varchar(10) DEFAULT '0' COMMENT '系统网点编号',
                                   zxha	: String, // varchar(10) DEFAULT NULL COMMENT '座席号',
                                   cshiid	: String, // bigint(40) DEFAULT NULL COMMENT '市id',
                                   xzhenid	: String, // varchar(100) DEFAULT NULL COMMENT '乡镇id',
                                   sfenid	: String, // bigint(20) DEFAULT NULL COMMENT '省份id',
                                   xianid	: String, // bigint(40) DEFAULT NULL COMMENT '县id',
                                   xxlyid	: String, // bigint(64) DEFAULT NULL COMMENT '信息来源id',
                                   xslxid	: String, // varchar(20) DEFAULT NULL COMMENT '销售类型id',
                                   yhsxid	: String, // varchar(20) DEFAULT NULL COMMENT '用户属性id',
                                   organizationname	: String, // varchar(80) DEFAULT NULL COMMENT '提货仓库名称',
                                   organizationaddress	: String, // varchar(800) DEFAULT NULL COMMENT '提货仓库地址',
                                   name	: String, // varchar(80) DEFAULT NULL COMMENT '仓库负责人姓名',
                                   mobile	: String, // varchar(12) DEFAULT NULL COMMENT '仓库负责人电话',
                                   retailsign	: String, // varchar(2) DEFAULT NULL COMMENT '是否新零售',
                                   appointmentkssj	: String, // datetime DEFAULT NULL COMMENT '预约配送开始时间',
                                   appointmentjssj	: String, // datetime DEFAULT NULL COMMENT '预约配送结束时间',
                                   wcsj	: String,// datetime DEFAULT NULL COMMENT '配送完成时间',
                                   requisition : String,
                                   shopno : String , // varchar(10) DEFAULT NULL COMMENT '店铺编号',
                                   shopname : String ,// varchar(40) DEFAULT NULL COMMENT '店铺名称'
                                   ts : String ,//数据日志时间戳
                                   table : String //表名称
     )








