package com.gree.util

import java.util

import com.gree.model.{AZMaxOrder, AzDataChaoShi}
import org.slf4j.{Logger, LoggerFactory}


object JsonBeanUtil {
  private val numberFormatUtil = new NumberFormatUtil()
  private val logger: Logger = LoggerFactory.getLogger(JsonBeanUtil.getClass)
  def getAzkbTimeoutOrdersJson(azDataChaoShi: AzDataChaoShi): util.HashMap[String, Any] = {
    this.synchronized {
      val json = new java.util.HashMap[String, Any]
      try {
        json.put("pgguid", azDataChaoShi.pgguid)
        json.put("created_by", azDataChaoShi.created_by)
        json.put("created_date", azDataChaoShi.created_date)
        json.put("last_modified_by", azDataChaoShi.last_modified_by)
        json.put("last_modified_date", azDataChaoShi.last_modified_date)
        json.put("pgid", azDataChaoShi.pgid)
        json.put("yhmc", azDataChaoShi.yhmc)
        json.put("yddh", azDataChaoShi.yddh)
        json.put("yddh2", azDataChaoShi.yddh2)
        json.put("quhao", azDataChaoShi.quhao)
        json.put("dhhm", azDataChaoShi.dhhm)
        json.put("fjhm", azDataChaoShi.fjhm)
        json.put("email", azDataChaoShi.email)
        json.put("sfen", azDataChaoShi.sfen)
        json.put("cshi", azDataChaoShi.cshi)
        json.put("xian", azDataChaoShi.xian)
        json.put("xzhen", azDataChaoShi.xzhen)
        json.put("dizi", azDataChaoShi.dizi)
        json.put("xxqd", azDataChaoShi.xxqd)
        json.put("xxly", azDataChaoShi.xxly)
        json.put("xxlb", azDataChaoShi.xxlb)
        json.put("beiz", azDataChaoShi.beiz)
        json.put("yhsx", azDataChaoShi.yhsx)
        json.put("yxji", azDataChaoShi.yxji)
        json.put("gdhao", azDataChaoShi.gdhao)
        json.put("spid", azDataChaoShi.spid)
        json.put("spmc", azDataChaoShi.spmc)
        json.put("azren", azDataChaoShi.azren)
        json.put("azrenid", azDataChaoShi.azrenid)
        json.put("azwdxtbh", azDataChaoShi.azwdxtbh)
        json.put("azwdno", azDataChaoShi.azwdno)
        json.put("azwdmc", azDataChaoShi.azwdmc)
        json.put("cjdt", numberFormatUtil.panduanDate(azDataChaoShi.cjdt))
        json.put("jspgwdno", azDataChaoShi.jspgwdno)
        json.put("jspgwdmc", azDataChaoShi.jspgwdmc)
        json.put("jspgwdxtbh", azDataChaoShi.jspgwdxtbh)
        json.put("jspgwdsj", azDataChaoShi.jspgwdsj)
        json.put("zxha", azDataChaoShi.zxha)
        json.put("ssqy", azDataChaoShi.ssqy)
        json.put("qqlyno", azDataChaoShi.qqlyno)
        json.put("qqlymc", azDataChaoShi.qqlymc)
        json.put("qqlyxh", azDataChaoShi.qqlyxh)
        json.put("qqlyzj", azDataChaoShi.qqlyzj)
        json.put("bjustat", numberFormatUtil.panduanInt(azDataChaoShi.bjustat))
        json.put("yhqwkssj", azDataChaoShi.yhqwkssj)
        json.put("yhqwjssj", azDataChaoShi.yhqwjssj)
        json.put("stat", numberFormatUtil.panduanInt(azDataChaoShi.stat))
        json.put("gpsdzxx", azDataChaoShi.gpsdzxx)
        json.put("cjren", azDataChaoShi.cjren)
        json.put("cjrmc", azDataChaoShi.cjrmc)
        json.put("cjwdno", azDataChaoShi.cjwdno)
        json.put("cjwdxtbh", azDataChaoShi.cjwdxtbh)
        json.put("zjczren", azDataChaoShi.zjczren)
        json.put("zjczwd", azDataChaoShi.zjczwd)
        json.put("zjczwdxtbh", azDataChaoShi.zjczwdxtbh)
        json.put("zjczsj", azDataChaoShi.zjczsj)
        json.put("xslx", azDataChaoShi.xslx)
        json.put("lcid", azDataChaoShi.lcid)
        json.put("djlxno", azDataChaoShi.djlxno)
        json.put("yyazsj", azDataChaoShi.yyazsj)
        json.put("sfwcps", azDataChaoShi.sfwcps)
        json.put("xsdh", azDataChaoShi.xsdh)
        json.put("gcbh", azDataChaoShi.gcbh)
        json.put("gcmc", azDataChaoShi.gcmc)
        json.put("azsl", numberFormatUtil.panduanInt(azDataChaoShi.azsl))
        json.put("wwsl", numberFormatUtil.panduanInt(azDataChaoShi.wwsl))
        json.put("lxren", azDataChaoShi.lxren)
        json.put("xsdwno", azDataChaoShi.xsdwno)
        json.put("xswdmc", azDataChaoShi.xswdmc)
        json.put("xsdwxtbh", azDataChaoShi.xsdwxtbh)
        json.put("fphm", azDataChaoShi.fphm)
        json.put("gmsj", azDataChaoShi.gmsj)
        json.put("kqbh", azDataChaoShi.kqbh)
        json.put("xsorsh", numberFormatUtil.panduanInt(azDataChaoShi.xsorsh))
        json.put("dqjdsj", azDataChaoShi.dqjdsj)
        json.put("syjd", azDataChaoShi.syjd)
        json.put("dqjd", azDataChaoShi.dqjd)
        json.put("jindu", azDataChaoShi.jindu)
        json.put("weidu", azDataChaoShi.weidu)
        json.put("shsj", azDataChaoShi.shsj)
        json.put("sfygllc", numberFormatUtil.panduanInt(azDataChaoShi.sfygllc))
        json.put("xslxid", azDataChaoShi.xslxid)
        json.put("yhsxid", azDataChaoShi.yhsxid)
        json.put("xxlbid", azDataChaoShi.xxlbid)
        json.put("xxlyid", azDataChaoShi.xxlyid)
        json.put("sfenid", azDataChaoShi.sfenid)
        json.put("cshiid", azDataChaoShi.cshiid)
        json.put("xianid", azDataChaoShi.xianid)
        json.put("xzhenid", azDataChaoShi.xzhenid)
        json.put("wcsj",numberFormatUtil.panduanDate(azDataChaoShi.wcsj))
        json.put("retailsign",numberFormatUtil.panduanInt1(azDataChaoShi.retailsign))
        json.put("servicewdmc",azDataChaoShi.servicewdmc)
        json.put("shopname",azDataChaoShi.shopname)
        json.put("orderphone",azDataChaoShi.orderphone)
        json.put("extendfiled1",azDataChaoShi.extendfiled1)
        json.put("extendfiled2",azDataChaoShi.extendfiled2)
        json.put("extendfiled3",azDataChaoShi.extendfiled3)
        json.put("extendfiled4",azDataChaoShi.extendfiled4)
        json.put("servicewdno",azDataChaoShi.servicewdno)
        json.put("shopno",azDataChaoShi.shopno)
        json.put("extendfiled5",azDataChaoShi.extendfiled5)
        json.put("cljggz", azDataChaoShi.cljggz)
        json.put("appointmentkssj", numberFormatUtil.panduanDate(azDataChaoShi.appointmentkssj))
        json.put("appointmentjssj", numberFormatUtil.panduanDate(azDataChaoShi.appointmentjssj))
        json.put("yqwangongtime", numberFormatUtil.panduanDate(azDataChaoShi.yqwangongtime))
        json.put("chaoshishichang", azDataChaoShi.chaoshishichang)
        json.put("shijiwangongtime",azDataChaoShi.shijiwangongtime)
        json.put("level1", azDataChaoShi.level1)
        json.put("level2", azDataChaoShi.level2)
        json.put("level3", azDataChaoShi.level3)
        json.put("level4", azDataChaoShi.level4)
        json.put("level5", azDataChaoShi.level5)
        json.put("level6", azDataChaoShi.level6)
        json.put("level7", azDataChaoShi.level7)
        json.put("level8", azDataChaoShi.level8)
        json.put("level9", azDataChaoShi.level9)
        json.put("level10", azDataChaoShi.level10)
        json.put("level11", azDataChaoShi.level11)
        json.put("level12", azDataChaoShi.level12)
        json.put("level13", azDataChaoShi.level13)
        json.put("level14", azDataChaoShi.level14)
        json.put("organizationaddress", azDataChaoShi.organizationaddress)
        json.put("organizationname", azDataChaoShi.organizationname)
      } catch {
        case e: Exception => logger.error("超时表出现异常" + e.getMessage)
      }
      json
    }
  }

  //输出最大的index
  def getAzkbMaxBigKuanBiaoJson(azMaxOrder: AZMaxOrder): util.HashMap[String, Any] = {
    this.synchronized {
      val json = new java.util.HashMap[String, Any]
      try {

        json.put("pgguid", azMaxOrder.pgguid)
        json.put("created_by", azMaxOrder.created_by)
        json.put("created_date", azMaxOrder.created_date)
        json.put("last_modified_by", azMaxOrder.last_modified_by)
        json.put("last_modified_date", azMaxOrder.last_modified_date)
        json.put("pgid", azMaxOrder.pgid)
        json.put("yhmc", azMaxOrder.yhmc)
        json.put("yddh", azMaxOrder.yddh)
        json.put("yddh2", azMaxOrder.yddh2)
        json.put("quhao", azMaxOrder.quhao)
        json.put("dhhm", azMaxOrder.dhhm)
        json.put("fjhm", azMaxOrder.fjhm)
        json.put("email", azMaxOrder.email)
        json.put("sfen", azMaxOrder.sfen)
        json.put("cshi", azMaxOrder.cshi)
        json.put("xian", azMaxOrder.xian)
        json.put("xzhen", azMaxOrder.xzhen)
        json.put("dizi", azMaxOrder.dizi)
        json.put("xxqd", azMaxOrder.xxqd)
        json.put("xxly", azMaxOrder.xxly)
        json.put("xxlb", azMaxOrder.xxlb)
        json.put("beiz", azMaxOrder.beiz)
        json.put("yhsx", azMaxOrder.yhsx)
        json.put("yxji", azMaxOrder.yxji)
        json.put("gdhao", azMaxOrder.gdhao)
        json.put("spid", azMaxOrder.spid)
        json.put("spmc", azMaxOrder.spmc)
        json.put("azren", azMaxOrder.azren)
        json.put("azrenid", azMaxOrder.azrenid)
        json.put("azwdxtbh", azMaxOrder.azwdxtbh)
        json.put("azwdno", azMaxOrder.azwdno)
        json.put("azwdmc", azMaxOrder.azwdmc)
        json.put("jspgwdno", azMaxOrder.jspgwdno)
        json.put("jspgwdmc", azMaxOrder.jspgwdmc)
        json.put("jspgwdxtbh", azMaxOrder.jspgwdxtbh)
        json.put("jspgwdsj", azMaxOrder.jspgwdsj)
        json.put("zxha", azMaxOrder.zxha)
        json.put("ssqy", azMaxOrder.ssqy)
        json.put("qqlyno", azMaxOrder.qqlyno)
        json.put("qqlymc", azMaxOrder.qqlymc)
        json.put("qqlyxh", azMaxOrder.qqlyxh)
        json.put("qqlyzj", azMaxOrder.qqlyzj)
        json.put("bjustat", numberFormatUtil.panduanInt(azMaxOrder.bjustat))
        json.put("yhqwkssj", azMaxOrder.yhqwkssj)
        json.put("yhqwjssj", azMaxOrder.yhqwjssj)
        json.put("stat", numberFormatUtil.panduanInt(azMaxOrder.stat))
        json.put("gpsdzxx", azMaxOrder.gpsdzxx)
        json.put("cjren", azMaxOrder.cjren)
        json.put("cjrmc", azMaxOrder.cjrmc)
        json.put("cjdt", azMaxOrder.cjdt)
        json.put("cjwdno", azMaxOrder.cjwdno)
        json.put("cjwdxtbh", azMaxOrder.cjwdxtbh)
        json.put("zjczren", azMaxOrder.zjczren)
        json.put("zjczwd", azMaxOrder.zjczwd)
        json.put("zjczwdxtbh", azMaxOrder.zjczwdxtbh)
        json.put("zjczsj", azMaxOrder.zjczsj)
        json.put("xslx", azMaxOrder.xslx)
        json.put("lcid", azMaxOrder.lcid)
        json.put("djlxno", azMaxOrder.djlxno)
        json.put("yyazsj", azMaxOrder.yyazsj)
        json.put("sfwcps", azMaxOrder.sfwcps)
        json.put("xsdh", azMaxOrder.xsdh)
        json.put("gcbh", azMaxOrder.gcbh)
        json.put("gcmc", azMaxOrder.gcmc)
        json.put("azsl", numberFormatUtil.panduanInt(azMaxOrder.azsl))
        json.put("wwsl", numberFormatUtil.panduanInt(azMaxOrder.wwsl))
        json.put("lxren", azMaxOrder.lxren)
        json.put("xsdwno", azMaxOrder.xsdwno)
        json.put("xswdmc", azMaxOrder.xswdmc)
        json.put("xsdwxtbh", azMaxOrder.xsdwxtbh)
        json.put("fphm", azMaxOrder.fphm)
        json.put("gmsj", azMaxOrder.gmsj)
        json.put("kqbh", azMaxOrder.kqbh)
        json.put("xsorsh", numberFormatUtil.panduanInt1(azMaxOrder.xsorsh))
        json.put("dqjdsj", azMaxOrder.dqjdsj)
        json.put("syjd", azMaxOrder.syjd)
        json.put("dqjd", azMaxOrder.dqjd)
        json.put("jindu", azMaxOrder.jindu)
        json.put("weidu", azMaxOrder.weidu)
        json.put("shsj", azMaxOrder.shsj)
        json.put("sfygllc", numberFormatUtil.panduanInt(azMaxOrder.sfygllc))
        json.put("xslxid", azMaxOrder.xslxid)
        json.put("yhsxid", azMaxOrder.yhsxid)
        json.put("xxlbid", azMaxOrder.xxlbid)
        json.put("xxlyid", azMaxOrder.xxlyid)
        json.put("sfenid", azMaxOrder.sfenid)
        json.put("cshiid", azMaxOrder.cshiid)
        json.put("xianid", azMaxOrder.xianid)
        json.put("xzhenid", azMaxOrder.xzhenid)
        json.put("wcsj", azMaxOrder.wcsj)
        json.put("retailsign", numberFormatUtil.panduanInt1(azMaxOrder.retailsign))
        json.put("servicewdmc", azMaxOrder.servicewdmc)
        json.put("shopname", azMaxOrder.shopname)
        json.put("orderphone", azMaxOrder.orderphone)
        json.put("extendfiled1", azMaxOrder.extendfiled1)
        json.put("extendfiled2", azMaxOrder.extendfiled2)
        json.put("extendfiled3", azMaxOrder.extendfiled3)
        json.put("extendfiled4", azMaxOrder.extendfiled4)
        json.put("servicewdno", azMaxOrder.servicewdno)
        json.put("shopno", azMaxOrder.shopno)
        json.put("extendfiled5", azMaxOrder.extendfiled5)
        json.put("appointmentkssj", azMaxOrder.appointmentkssj)
        json.put("appointmentjssj", azMaxOrder.appointmentjssj)
        json.put("tbl_Az_Assign_Fkmx", azMaxOrder.tbl_Az_Assign_Fkmx)
        json.put("tbl_Az_Assign_Mx", azMaxOrder.tbl_Az_Assign_Mx)
        json.put("tbl_Az_Assign_Satisfaction", azMaxOrder.tbl_Az_Assign_Satisfaction)
        json.put("tbl_Az_Assign_Appointment", azMaxOrder.tbl_Az_Assign_Appointment)
        json.put("tbl_Az_Assign_Fee", azMaxOrder.tbl_az_assign_fee)
        json.put("tbl_Az_Assign_Lc_Fzry", azMaxOrder.tbl_az_assign_lc_fzry)
        json.put("tbl_Trade_New_For_Old", azMaxOrder.tbl_trade_new_for_old)
        json.put("tbl_Yjhx_Jdd", azMaxOrder.tbl_yjhx_jdd)
        json.put("level1", azMaxOrder.level1)
        json.put("level2", azMaxOrder.level2)
        json.put("level3", azMaxOrder.level3)
        json.put("level4", azMaxOrder.level4)
        json.put("level5", azMaxOrder.level5)
        json.put("level6", azMaxOrder.level6)
        json.put("level7", azMaxOrder.level7)
        json.put("level8", azMaxOrder.level8)
        json.put("level9", azMaxOrder.level9)
        json.put("level10", azMaxOrder.level10)
        json.put("level11", azMaxOrder.level11)
        json.put("level12", azMaxOrder.level12)
        json.put("level13", azMaxOrder.level13)
        json.put("level14", azMaxOrder.level14)
        json.put("yqwangongtime", azMaxOrder.yqwangongtime)
        json.put("wcsj1", numberFormatUtil.panduanDate(azMaxOrder.wcsj))
        json.put("organizationaddress", azMaxOrder.organizationaddress)
        json.put("organizationname", azMaxOrder.organizationname)
        json.put("platform_bizorderid", azMaxOrder.platformBizorderid)
        json.put("fkmx_lastest_message", azMaxOrder.fkmxLastestMessage)

      } catch {
        case e: Exception => logger.error("数据输出到AZ最大的index异常->" + e.getMessage)
      }
      json
    }
  }
}
